version: '2'

services:
  nginx:
    build: ../
    environment:
      - NGINX_PORT=80
    networks:
      - proxy
    container_name: admin-nginx
    expose:
      - 80
    labels:
      - "traefik.port=80"
      - 'traefik.backend=gestionale-admin'
      - 'traefik.enable=true'
      - "traefik.frontend.rule=Host:admin.tridentescarface.com"

networks:
  proxy:
    external: true